### ISSUE TITLE
css2json-loader and export

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-dev-webpack#1120]
In my app i do something like this is sass
```scss
$primary-color: #2196F3;
:export {
    primaryColor: $primary-color;
  }
```
The idea is to be able to require within javascript like this
```ts
import { locals } from '~/variables.scss';
export const primaryColor: string = locals.primaryColor;
```
Now `primaryColor` is available everywhere.

However this works when i use `css-loader` but not when i use `nativescript-dev-webpack/css2json-loader`.
Do you have any idea on how i can make it work

**Comment by edusperoni** [comment]
This is my solution (I'm using the older version but it'll work with css2json-loader):

```javascript
                // add /\.module\.scss$/i to exclude!
                { test: /\.scss$/, exclude: [/[\/|\\]app\.scss$/, /\.module\.scss$/i], use: ["raw-loader", "resolve-url-loader", "sass-loader"] },
                {
                    test: /\.module\.scss$/i, use: [
                        {
                        loader: "css-loader",
                        options: {
                            url: false
                        }
                    }, "sass-loader"]
                },
```

We create `my.module.scss` with:
```scss
@import "../../app-variables";

:export {
    accent: $accent-dark;
}
```

If anyone knows of a better solution, it'd be nice!
