### ISSUE TITLE
Imported CSS files paths are resolved differently with or without --bundle

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-dev-webpack#545]
Imported CSS files are using relative vs absolute paths depending on if the build is CLI or with Webpack.
For example, let's assume we have a CSS file in `app/views/style-common.css`  which will be imported in 'app/views/sub-page.android.css'
```CSS
/* Not working with Webpack; Working with CLI build */
@import url("~/views/style-common.css");

/* Working with Webpack; Not Working with CLI build */
@import url("./style-common.css");


Label {
    background-color: brown;
    color: whitesmoke;
}
```

Steps to reporudece:
- use [this test app](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-dev-webpack/nestedCSsImports)
- build with `tns run android` and then build with `tns run android --bundle`. Both cases are requiring to change the CSS import path so that the styles from `style-common.css` can be loaded.

Note: this happens only when the views are **nested** (CSS on root level is working as both paths are identical)
