### ISSUE TITLE
Background image not showing in iOS ActionBar

### ISSUE THREAD

**Issue by sissingclay** [NativeScript/nativescript-dev-webpack#874]
Please refers this issue[https://github.com/NativeScript/nativescript-dev-webpack/issues/296](url)

Hi @NickIliev,

I've tested this and have found that there is a problem with iOS ActionBar background image. I've pulled this repo to check and changed the background colour to pink as the previous colour was too close to the background image colour to notice a difference.

Please see attached image.
![56676566-77b5e080-66b6-11e9-9bb1-d257557172f7](https://user-images.githubusercontent.com/8215370/56754568-4c4df700-6785-11e9-9463-0bd8f8f0d37b.png)

**Comment by NickIliev** [comment]
@sissingclay indeed it seems at this point (tested with tns-core-modules@5.3.1) the ActionBar is not supporting background-image directly. However, you could easily create a custom ActionBar layout like this

```HTML
<ActionBar title="Home" class="action-bar">
    <StackLayout class="my-bar" width="100%" height="100%"></StackLayout>
</ActionBar>
```

where the CSS is something like this:
```CSS
.action-bar {
    background-color: green;
}

.my-bar {
    color: #F00;
    font-size: 24;
    text-align: center;
    background-image: url("https://d2odgkulk9w7if.cloudfront.net/images/default-source/logos/ns-logo-shadowed-min.png?sfvrsn=16b60efe_2");
    background-repeat: no-repeat;
    background-position: center;
    background-size:cover;
}
```


Here is [a Playground app](https://play.nativescript.org/?template=play-ng&id=W18HeG) demonstrating the above
