### ISSUE TITLE
CSS styles for elements selectors are not applied when element is registered (e.g. CardView))

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-dev-webpack#913]
Styles of the following type (element selector) are not applied when building with uglify
```CSS
CardView {
    background-color: slateblue;
}

CardView > GridLayout {
    background-color: green;
}
```

The cardview element (from `nativescript-cardview`) [is registered via Angular's `registerElement`](https://github.com/NickIliev/nativescript-ng-cosmos/blob/e4310a16048c520016f0360486faaa1f8f501cb0/app/app.module.ts#L15)

Then we are building with the following command (Webpack enabled by default)

```Shell
 tns run android --env.uglify
```

As a result, the above CSS won't be applied. Works as expected when the uglify flag is **not** provided. Test project demonstrating the above can be found [here](Test project demonstrating the above can be found [here](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/NativeScript/issue-7286)
)
